"""
**Q) What is Guessing Game  ?** 

⇒ In guessing Game we will trying to generate a random number that number will call as a jackpot number . 

As the user what we do , we will just try to guess that particular number . 


**Example:**


**Guessing Game program :**

Let’s say program generated one number called 10. Now this particular program will ask for the input from user so, user have to pass one input like what is the particular number actually so, here user have to pass that particular jackpot number or guess that particular number , let’s say user have given a number 8 , then program will tell user it’s lower number try to guess something higher . Now let’s say user have guessed number 20 , then program will tell user it’s a higher number try to guess something lower . Now let’s say user have given number 10 , that means this particular number 10 and our program generated jackpot number is 10 and it is matching together , then program will tell user that your guess is correct . 

This program will be implementing with the help of this particular **while loop concept** and apart from while loop , we will be also using **conditional statement** .

⇒ 

**To make the programming more easy for us :**

First of all try to note down what are the functionality we want to implement in this particular game . 

i) Generate a random number between 1 to 100 . 

ii) Take an input from user then user will pass a number .

iii) After that we have to compare / match that user number with Generated number. 

iv) If user number is correct ‘ show results ’ .

v) If user number is not correct then we have to tell user that it’s a lower number or higher number .

"""

# Code :

# i) Generate a random number between 1 to 100 . 

import random     # random module is used to generate random number 

jackpot = random.randint(1,100)   # randint function is used to generate random number between 1 to 100 .
                                    # jackpot is a variable which will store the random number generated by randint function .

# print(jackpot)   # it will print the random number generated by randint function .

# ii) Take an input from user then user will pass a number .

guess_number = int(input("Enter the number between 1 to 100 :"))   # input function is used to take input from user .

# iii) After that we have to compare / match that user number with Generated number.

counter = 1  # counter is a variable which will store the number of attempts user have taken to guess the number .

while guess_number != jackpot:   # != is not equal to operator , if user number is not equal to jackpot number then it will execute the loop

    if guess_number < jackpot:   # if user number is less than jackpot number then it will print lower number
        print("Wrong! Please try to guess higher number")
    else:
        print("Wrong! Please try to guess lower number")

    guess_number = int(input("Enter the number between 1 to 100 :"))   # input function is used to take input from user .
    counter += 1   # increment of counter variable .

# iv) If user number is correct ‘ show results ’ .

else:         # else is used to execute the block of code if the condition of while loop becomes false . 
    print("Congratulations! Your guess is correct")   # it will print the message if user number is correct .
    print("Your attempt is :",counter)   # it will print the number of attempts user have taken to guess the number .







